config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'home#index'
  
  get 'home', to: 'home#index'

  get 'clothings', to: 'clothings#index'

  resources :clothings do
    resources :clothing_clothing_types
    resource :clothing_wanted_clothings
    resource :pictures
  end

  resources :user_wanted_clothes
  

end

app/models/clothing.rb
class Clothing < ActiveRecord::Base
  belongs_to :user
  belongs_to :clothing_type
  belongs_to :size
  belongs_to :color
  belongs_to :clothing_brand
  has_many :clothing_clothing_types
  has_many :pictures
  has_many :clothing_wanted_clothings
  accepts_nested_attributes_for :pictures

  has_many :exchangeable_clothing_types, through: :clothing_clothing_types, source: :clothing_type

  validates :clothing_type_id, presence: true
  validates :size_id, presence: true
  validates :color_id, presence: true
  validates :owner_id, presence: true

  validates_associated :pictures
  validates :pictures, presence: true

  def self.get_other_users_clothes uid
    where.not(owner_id: uid).order(created_at: :desc).all
  end

  def self.get_user_items uid
    where(owner_id: uid.to_i).order(created_at: :desc).all
  end

  def get_all_items_of_types clothing_type_ids, uid
    where.not(owner_id: uid).where(clothing_type_id: clothing_type_ids)
  end

  def matching_clothes
    clothings = Clothing.
        joins("LEFT JOIN clothing_clothing_types ON clothing_clothing_types.clothing_id = clothings.id").
        where("clothing_clothing_types.id IS NULL OR clothing_clothing_types.clothing_type_id = ?", clothing_type_id).
        where.not(owner_id: owner_id)

    if exchangeable_clothing_type_ids.any?
      clothings.where(clothing_type_id: exchangeable_clothing_type_ids)
    else
      clothings
    end
  end
end

app/models/clothing_type.rb
class ClothingType < ActiveRecord::Base
  def get_clothing_type type
    ClothingType.find_by name: type
  end

  def create_clothing_type type
    ClothingType.create name: type
  end
end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
  respond_to :html, :js
  before_filter :require_user

  include ClothingHelper
  include UserWantedClothingHelper

  def index
    @user_clothes = Clothing.get_user_items(current_user.id)
  end

  def show
    render Clothing.find params[:id]
  end

  def new
    @clothing = Clothing.new
    @clothing.pictures.build
  end

  def create
    @clothing = Clothing.new(user_added_clothing_params)

    if @clothing.save
      flash[:notice] = "Clothing is created"
      redirect_to clothings_path
    else
      all = []
      errors = @clothing.errors.full_messages.to_sentence
      flash.now[:notice] = errors
      render action: "new"
    end
  end

  def destroy
    # TBD. Handle exception here when user wants to delete someone else's clothes
    item_of_clothes = current_user.clothing.find(params[:id])

    if item_of_clothes.nil?
      flash[:notice] = "Hey! What are you doing?"
    else
      item_of_clothes.pictures.destroy
      item_of_clothes.destroy
      flash[:success] = "User is deleted"
    end

    redirect_to clothings_path
  end

  def user_added_clothing_params
    all_params = params[:clothing].merge(owner_id: current_user.id)
    all_params.permit(:color_id, :size_id, :clothing_type_id, :owner_id, :clothing_brand_id, exchangeable_clothing_type_ids: [], pictures_attributes: [:picture, :picture_cache])
  end
end

app/helpers/clothing_helper.rb
module ClothingHelper

  def isArticleOfClothesExists id
    Clothing.exists?(id)
  end

end

app/views/clothings/_clothing.html.erb
  <%= image_tag clothing_picture(clothing), size: "100x100"%>

  <ul class="list-group clothing-params">
      <li>
          <div class="clothes-type"><%= clothing_name(clothing) %></div>
      </li>
      <li>
        <div class="clothes-brand"><%= clothing_brand(clothing) %></div>
      </li>
      <li>
          <%= clothing_size(clothing) %>
      </li>
      <li>
          <%= clothing_color(clothing) %>
      </li>
      <li> Likes:
        <%= clothes_likes(clothing) %>
      </li>
  </ul>

  <ul class="list-inline">
      <% expected_clothing_names(clothing).each do |match|%>
          <li>
            <span class="clothing-type"><%= match %></span>
          </li>
      <% end %>
      <li>
        <% if expected_clothing_names(clothing).to_a.empty? %>
            <span class="clothing-type">Any</span>
        <%end%>
      </li>
  </ul>
  <!--Here I am not sure if it removes a picture. If not implement.-->
  <!--Dependent destroy to use for deleting the pictures-->
  <%if(clothing.owner_id == current_user.id)%>
    <%= link_to "Remove", clothing, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you would like to remove this Clothing?" }%>
    <%= link_to "Exchangeable", clothing_clothing_clothing_types_path(clothing)%>
  <%end%>

app/views/clothings/index.html.erb
<div class="container">
  <header>
    <div>Your personal Dressing Room on Exclothed</div>
    <p><small> Add your clothes. Manage your clothes. Find articles of clothes for exchange. And finally exchange your clothes.</small></p>
  </header>


  <!--Own clothes-->

  <div class="container-fluid">
    <div class="kerzon-text"><h2>Your Clothes </h2></div>
    <div class="kerzon"></div>
  </div>

    <% @user_clothes.each do |user_clothes| %>
        <div class="container-fluid home-transition">
          <div class="row-fluid">
            <div class="users-clothes-container">
              <%= render partial: 'clothings/clothing', object: user_clothes %>
            </div>
          </div>
        </div>
    <% end %>

  <!--Liked clothes-->

    <div class="container-fluid">
      <div class="kerzon-text"><h2>Clothes you liked </h2></div>
      <div class="kerzon"></div>
    </div>

    <div class="container-fluid">
        <% if current_user.user_wanted_clothes.empty? %>
            <%= "You want no clothes?" %>
        <% else %>
          <% current_user.user_wanted_clothes.each do |wanted_clothes|%>
              <%if isArticleOfClothesExists(wanted_clothes.wanted_clothes_id)%>
                  <div class="wanted-clothes-container">
                    <%= render partial: 'home/clothes', object: Clothing.find(wanted_clothes.wanted_clothes_id) %>
                  </div>
              <%end%>
          <% end %>
        <% end %>
    </div>
</div>

app/views/clothings/new.html.erb
<div class="container">
  <header>
    <div> Why wouldn't you add your piece of clothes?</div>
    <p><small>It will be visible on the home page for other users. They will be able to like it or send you a request to initiate exchanging.</small></p>
  </header>

  <div class="col-md-4 col-md-offset-4 ">
      <%= form_for @clothing, html: {multipart:true} do |f| %>
          <div class="form-group">
            Type:
            <%= f.select :clothing_type_id, ClothingType.all.collect { |p| [p.name, p.id]},
                         { include_blank: "Select ..."},
                         {class: "form-control"} %>
          </div>

           <div>
            Brand:
            <%= f.select :clothing_brand_id, ClothingBrand.all.collect { |p| [p.name, p.id]},
                         { include_blank: "Select ..."},
                {class: "form-control"} %>
          </div>
          <div>
            Color:
            <%= f.select :color_id, Color.all.collect { |c| [c.name, c.id] },
                                    { include_blank: "Select ..."},
                                    { class: "form-control"} %>
          </div>

          <div>
            Size:
            <%= f.select :size_id, Size.all.collect { |s| [s.name, s.id] },
                                       { include_blank: "Select ..." },
                                       { class: "form-control"} %>
          </div>

          <div>
            I want to exchange this clothes to:
            <p><small>Choose "Any" if you do not know yet what you would like to get in return.</small> </p>

            <%= f.select :exchangeable_clothing_type_ids,
                         ClothingType.all.collect { |e| [e.name, e.id] },
                                       {:prompt => "Any"},
                                      {
                                      class: "form-control",
                                      multiple: true}%>
          </div>
          <div><p>
            Upload a picture of your piece of clothes:
            <%= f.fields_for :pictures, html: { multipart: true } do |picture| %>
                <%=picture.file_field  :picture%>
                <%= picture.hidden_field :picture_cache %>
            <%end%></p>
          </div>
          <% current_user.id %>
          <%=f.submit "Add", {class: "btn btn-default"}%>
          <%=link_to "Cancel", home_path %>
      <% end %>
  </div>
</div>