config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'home#index'
  
  get 'home', to: 'home#index'

  get 'clothings', to: 'clothings#index'

  resources :clothings do
    resources :clothing_clothing_types
    resource :clothing_wanted_clothings
    resource :pictures
  end

  resources :user_wanted_clothes
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wardrobe</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--Custom-->
  <link href="https://fonts.googleapis.com/css?family=Lato:100normal,100italic,300normal,300italic,400normal,400italic,700normal,700italic,900normal,900italic&amp;subset=all" rel="stylesheet" type="text/css">
</head>
<body>
    <nav class="navbar">
      <div class="container">
        <div calss="navbar-header">
          <a href="/" class="navbar-brand">EXCLOTHED</a>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Dressing room", "/clothings" %></li>
          <li><%= link_to "Add clothes", new_clothing_path %></li>
          <li><a href="#"> <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></li>
        </ul>
        <% if current_user%>
          <div id="auth">
            <span><%= current_user.email%></span>
            <%= link_to "Logout", destroy_user_session_path, :method => :delete%>
          </div>
        <% end %>
      </div>
    </nav>
    <div class="container ">
      <% if notice %>
        <div class="alert alert-warning"><%= notice %></div>
      <% end %>
      <%if alert%>
        <div class="alert alert-danger"><%= alert %></div>
      <%end%>
      <%if success%>
        <div class="alert alert-success"><%= success %></div>
      <%end%>
    </div>

<%= yield %>

<div class="navbar navbar-fixed-bottom">
  <div class="container">
      <p class="text-muted">Eco, brands and this lifestyle </p>
  </div>
<div/>

</body>
</html>